version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3333'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/mydatabase

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
